In [ ]:
#Generate 1000 random numbers. Out of which, create a double linked list of all prime numbers.

In [47]:
import numpy as np

In [26]:
gen = np.random.randint(low=1, high=1000, size=1000)

In [27]:
gen

array([772, 893,  56, 743,  23, 435, 725, 177, 262, 867, 823, 945, 823,
       180, 407, 846,  20, 630, 555, 543, 211, 407, 990, 372, 917, 321,
       990, 949, 985, 544, 978,  93, 156, 584, 766, 543, 145,  14, 379,
        83, 467, 409, 300,  29, 603,  21, 484, 677, 745, 464,  48, 749,
       908, 631, 172,  89, 166, 912,  14, 150, 309, 705, 189, 453,  27,
       930, 619, 565, 319, 193, 960, 334, 394, 209, 187, 141, 862, 334,
       787, 698, 654,  46, 144, 672,  68, 746, 965, 221, 995, 304, 266,
       163, 800,  71, 363, 524, 763, 764,  19, 412, 911, 211, 170, 268,
       123, 317, 162, 218, 435, 958, 505, 430,  15, 546, 708, 288, 496,
       947, 273, 728, 803, 261, 635,  51, 673, 712, 299, 151, 822,  29,
         7, 271, 992, 438, 706, 835, 132, 226, 717, 321, 736, 526, 236,
       963, 997, 774, 422,   9, 385, 161, 308, 828, 875,  39,  77,  61,
       367, 605,  51, 212,  92, 220, 990, 915,  70, 822,  96, 559, 698,
       296, 725, 804, 975, 301, 227, 820, 320, 219, 163, 783, 654, 664,
       623,  86, 376,  91, 952, 307, 793, 543, 277, 939, 423, 732,  68,
       383,  97,  89, 746, 309, 929, 813, 353, 745, 327, 361, 129, 133,
       297, 532, 798, 276, 764, 888, 604, 792,  27, 252, 134, 724,  91,
       415, 586, 310, 211, 211,  14, 518,  34, 241, 450, 208, 140, 250,
       142, 384, 471, 876,  10, 931, 903, 894, 739, 294,  83,  88, 731,
       531, 544, 331, 859, 610, 579,   6, 361, 939, 635, 400, 208, 996,
       774, 407, 866, 577, 588,  44, 712, 565, 339, 880, 900, 116, 833,
       649,  30, 572, 548, 202, 136, 231, 833, 478, 941, 499, 151,  61,
       797, 341, 169, 102, 704, 257, 151, 398, 359, 249, 159, 868, 248,
       649,   4, 446, 105, 862, 717, 815, 104, 251, 175, 516, 111, 674,
       844, 205, 879, 201, 482, 660, 110, 689,  72, 436, 669, 214, 612,
       252, 975,  55, 865, 861, 986, 539, 289, 840, 155, 137, 873, 136,
       924, 325, 613,  59, 582, 290, 101, 885, 582, 261, 257, 162, 797,
       549, 300, 747,  12, 557, 925, 713, 755, 765, 205, 324, 305, 305,
       485, 873, 597, 503, 707,  64, 553, 631, 409, 441, 532, 482, 353,
       656, 146, 917, 233, 978, 804, 245, 566, 805, 984, 333, 344, 671,
       260,  96, 465, 779, 226, 890, 122,  80, 765, 125, 257, 253, 757,
       220, 499, 635, 278,  50, 909, 300, 680, 327, 808, 244, 679, 772,
       600, 932, 664, 982, 722, 240,  48,  88, 831,  79, 820,  36, 352,
       535, 381, 769, 802, 710, 262, 539, 141,  64, 109, 592, 227, 972,
       860, 401, 847, 831, 222, 792, 205, 539, 197,  82, 850, 240,  47,
       285, 634, 427, 842, 445, 225, 292, 358, 448, 377, 553,  26, 896,
        15, 458, 911, 971, 136, 526, 108, 552, 815, 853, 255, 997, 851,
       877,  69, 940, 119, 862,  37, 707, 928, 505, 786, 862, 642, 905,
       902, 715, 870, 162, 792, 784, 902,  73, 632, 877, 881, 569, 241,
       152, 844,  94, 581, 866,  52, 971, 285, 540, 281, 916, 427, 374,
       666, 609, 148, 703, 232, 911, 981, 299, 761, 652, 637, 353, 217,
       104, 387, 835, 289, 634, 647, 202,  36, 338, 930, 926, 693, 872,
       418,  65, 252, 458, 847,  61, 990, 699, 548, 628, 600,  14,  68,
       862, 394, 518, 962, 688, 260,  59, 575, 114, 440, 762,  31, 830,
       475, 788, 176, 507,  77, 260, 915, 934, 436, 955, 955,  87, 316,
       404, 463, 713, 938, 610, 834, 589, 904,  40, 164, 700, 783, 645,
       984, 912,  63, 803, 940, 252, 125, 964, 214,  62, 850, 566, 930,
       217, 697, 380, 641, 592, 597, 514, 804, 659, 892, 669, 814, 290,
       655, 418, 742, 735, 508, 432, 271, 548, 446, 655, 464, 450, 917,
       621, 794, 543, 804,  98, 912, 555, 115, 898, 657, 685, 935, 407,
       368, 286, 790,  27, 234, 321, 660, 549, 783, 616, 614, 471,  55,
       675, 628, 116,  61,  11, 823, 177, 291, 174, 701, 219, 658, 897,
       469, 210, 337, 567, 445, 318, 715, 201, 306, 517, 830, 462, 460,
       892, 289,  91, 322, 932, 314, 320, 113, 201, 812, 572, 652, 376,
       309, 361, 182, 640, 709, 600, 860, 291,  98, 129, 526, 828, 704,
       953, 864, 743, 968, 762, 365, 652, 791, 207, 446, 836, 131, 140,
       912, 882, 557, 981, 874, 682, 235, 414, 573, 973, 185, 585, 180,
       476, 483, 122, 744, 368, 689, 783, 641, 640, 320, 207, 291,   1,
        32, 569, 729, 379, 284, 627, 505, 237, 570, 533, 568, 303, 866,
       837, 659, 128, 411, 905, 738, 523, 758, 149, 878, 355,   4, 494,
       288, 232, 947,  67, 469, 446, 748, 847, 633, 669, 804, 491, 665,
       720, 721,  29, 623, 423, 384,  81, 779, 322, 258, 320, 956, 485,
       446,  44, 814, 437, 633, 338, 905, 719, 802, 449,  31, 877, 397,
       526, 429, 347, 888, 376, 175, 952, 109, 321,  45, 832,  99, 973,
       571,  61, 262, 920, 313, 371, 155, 225, 816, 639, 993, 417, 169,
       983, 897,  22, 381, 745, 212, 319, 644, 767, 729, 509,  53, 189,
       626, 822, 579, 993, 805,  30, 904,  27, 207, 275, 155,   2, 611,
       698,  77, 200, 201, 495, 664, 746, 262, 215, 467, 518, 789, 668,
       152,  88, 406, 802, 302, 233, 123, 116, 616, 388, 168, 253,  41,
       758, 401, 500, 887, 356, 288, 803, 224, 919, 244, 877, 865, 898,
       659, 393, 828, 733,  58, 658,  77, 356, 336,  26, 395, 270, 215,
       146, 382,  96, 382, 847, 544, 964, 525, 900, 444,   3, 986, 684,
        13, 205, 758, 746,  71,  57, 509, 466, 989, 420,  74,  13, 294,
       129,  70, 291, 953, 417, 939, 498, 157, 462, 650, 974, 138, 378,
        19, 536, 692, 295, 240, 630, 916, 913, 119, 911,  14, 952, 679,
       676, 402, 297, 246, 589, 272, 564,   9, 317, 345, 346,  34, 654,
        11, 240, 411, 885, 593, 830, 188, 862,  62, 358, 489,  10])

In [35]:
prime = []
even = []
for i in gen:
    rem=i%2
    if rem==0:
        even.append(i)
    else:
        for div in range(2,i):
            rem=i%div
            if rem==0:
                break
            else:
                if div==i-1:
                    prime.append(i)

In [38]:
print(prime)

[743, 23, 823, 823, 211, 379, 83, 467, 409, 29, 677, 631, 89, 619, 193, 787, 163, 71, 19, 911, 211, 317, 947, 673, 151, 29, 7, 271, 997, 61, 367, 227, 163, 307, 277, 383, 97, 89, 929, 353, 211, 211, 241, 739, 83, 331, 859, 577, 941, 499, 151, 61, 797, 257, 151, 359, 251, 137, 613, 59, 101, 257, 797, 557, 503, 631, 409, 353, 233, 257, 757, 499, 79, 769, 109, 227, 401, 197, 47, 911, 971, 853, 997, 877, 37, 73, 877, 881, 569, 241, 971, 281, 911, 761, 353, 647, 61, 59, 31, 463, 641, 659, 271, 61, 11, 823, 701, 337, 113, 709, 953, 743, 131, 557, 641, 569, 379, 659, 523, 149, 947, 67, 491, 29, 719, 449, 31, 877, 397, 347, 109, 571, 61, 313, 983, 509, 53, 467, 233, 41, 401, 887, 919, 877, 659, 733, 3, 13, 71, 509, 13, 953, 157, 19, 911, 317, 11, 593]

In [39]:
class train_coach:
    previous_hook = None
    a_number = None
    next_hook = None

In [40]:
number_of_nodes  = 0
first_coach = None
last_coach = None

In [41]:
def connect_coaches(class_instance, engine):
    global number_of_nodes
    global first_coach
    global last_coach
    
    if engine == last_coach:
        last_coach = class_instance
        first_coach = last_coach
    else:
        class_instance.previous_hook = last_coach
        last_coach.next_hook = class_instance
        last_coach = class_instance
    number_of_nodes = number_of_nodes + 1

In [43]:
engine = None

for number in prime:
    class_instance = train_coach()
    class_instance.a_number = number
    connect_coaches(class_instance, engine)

In [44]:
def print_linked_list(engine_address):
    if engine_address == None:
        return
    else:
        print (engine_address.a_number)
        print_linked_list(engine_address.next_hook)

In [45]:
def insert (loc,engine_address,value):
    global number_of_nodes
    global first_coach
    global last_coach
    
    #Insertion at last loc
    if loc == number_of_nodes:
        new_coach = train_coach()
        new_coach.a_number = value
        last_coach.next_hook = new_coach
        new_coach.previous_hook = last_coach
        last_coach = new_coach
        number_of_nodes = number_of_nodes + 1
        return
    
    #Insertion at Invalid loc
    if loc<0 or loc>number_of_nodes:
        print("You have asked to insert the element at an invalid location")
        return
    
    #Insertion at start
    if loc == 0:
        new_coach = train_coach()
        new_coach.a_number = value
        new_coach.next_hook = first_coach
        first_coach.previous_hook = new_coach
        first_coach = new_coach
        number_of_nodes = number_of_nodes + 1
        return
    
    #Insertion at any loc
    if loc == 1:
        new_coach = train_coach()
        new_coach.a_number = value
        temp_address = engine_address.next_hook
        engine_address.next_hook = new_coach
        new_coach.previous_hook = engine_address
        new_coach.next_hook = temp_address
        temp_address.previous_hook = new_coach
        number_of_nodes = number_of_nodes + 1
        return

In [46]:
print_linked_list(first_coach)

743
23
823
823
211
379
83
467
409
29
677
631
89
619
193
787
163
71
19
911
211
317
947
673
151
29
7
271
997
61
367
227
163
307
277
383
97
89
929
353
211
211
241
739
83
331
859
577
941
499
151
61
797
257
151
359
251
137
613
59
101
257
797
557
503
631
409
353
233
257
757
499
79
769
109
227
401
197
47
911
971
853
997
877
37
73
877
881
569
241
971
281
911
761
353
647
61
59
31
463
641
659
271
61
11
823
701
337
113
709
953
743
131
557
641
569
379
659
523
149
947
67
491
29
719
449
31
877
397
347
109
571
61
313
983
509
53
467
233
41
401
887
919
877
659
733
3
13
71
509
13
953
157
19
911
317
11
593